from tkinter import *
from PIL import ImageTk,Image

win = Tk()
win.geometry("1280x695") 
win.title("Face recognition")

def home():#create page2
    f2=Frame(bg="#003e53")
    f2.place(x=0,y=0,width='1280',height='695')
    label=Label(f2,text='home',width='40',height='1',font=('comicsansms 12 bold'),fg='black',bg='dark grey',borderwidth=10)
    label.pack(side='top') 
    btn=Button(f2,text='Add data set',width='40',height='1',font=('comicsansms 12 bold'),fg='black',bg='dark gray',borderwidth=10,command=data_set)
    btn.place(x=200,y=380)
    btn=Button(f2,text='photo detection',width='40',height='1',font=('comicsansms 12 bold'),fg='black',bg='dark grey',borderwidth=10,command= static_face_recognition)
    btn.place(x=200,y=440)
    btn=Button(f2,text='live video detection',width='40',height='1',font=('comicsansms 12 bold'),fg='black',bg='dark gray',borderwidth=10,command=live_video_face_recognition)
    btn.place(x=200,y=500)
    btn=Button(f2,text='Exit',width='40',height='1',font=('comicsansms 12 bold'),fg='black',bg='dark gray',borderwidth=10)
    btn.place(x=200,y=560)
    btn=Button(f2,text='Help',width='5',height='0',font=('comicsansms 12 bold'),fg='black',bg='dark gray',borderwidth=5)
    btn.place(x=0,y=0)
    
def data_set():#create page 3
    f3=Frame(bg="#003e53")   
    f3.place(x=0,y=0,width='1280',height='695')
    label=Label(f3,text='DATA SET WINDOW',width='40',height='1',font=('comicsansms 12 bold'),fg='black',bg='dark grey',borderwidth=10)
    label.pack(side='top') 
    f4=Frame()
    f4.place(x=580,y=50,width='640',height='400')
    btn=Button(f3,text='take photo',width='40',height='1',font=('comicsansms 12 bold'),fg='black',bg='dark grey',borderwidth=10)
    btn.place(x=60,y=150) 
    btn=Button(f3,text='choose from gallery',width='40',height='1',font=('comicsansms 12 bold'),fg='black',bg='dark grey',borderwidth=10)
    btn.place(x=60,y=220) 
    btn=Button(f3,text='trainnig data set',width='40',height='1',font=('comicsansms 12 bold'),fg='black',bg='dark grey',borderwidth=10)
    btn.place(x=60,y=290)
    btn=Button(f3,text='back',width='5',height='1',font=('comicsansms 12 bold'),fg='black',bg='dark grey',borderwidth=10,command=home)
    btn.pack(side="left",anchor="sw")  

def static_face_recognition():#create page 4
    f5=Frame(bg="#003e53")   
    f5.place(x=0,y=0,width='1280',height='695')
    label=Label(f5,text='DATA SET WINDOW',width='40',height='1',font=('comicsansms 12 bold'),fg='black',bg='dark grey',borderwidth=10)
    label.pack(side='top') 
    f6=Frame()
    f6.place(x=580,y=50,width='640',height='400')
    btn=Button(f5,text='take photo',width='40',height='1',font=('comicsansms 12 bold'),fg='black',bg='dark grey',borderwidth=10)
    btn.place(x=60,y=150) 
    btn=Button(f5,text='choose from gallery',width='40',height='1',font=('comicsansms 12 bold'),fg='black',bg='dark grey',borderwidth=10)
    btn.place(x=60,y=220) 
    btn=Button(f5,text='recognize',width='40',height='1',font=('comicsansms 12 bold'),fg='black',bg='dark grey',borderwidth=10)
    btn.place(x=60,y=290)
    btn=Button(f5,text='back',width='5',height='1',font=('comicsansms 12 bold'),fg='black',bg='dark grey',borderwidth=10,command=home)
    btn.pack(side="left",anchor="sw") 

def live_video_face_recognition():#create page 5
    f7=Frame(bg="#003e53")   
    f7.place(x=0,y=0,width='1280',height='695')
    label=Label(f7,text='LIVE VIDEO FACE RECOGNITION',width='40',height='1',font=('comicsansms 12 bold'),fg='black',bg='dark grey',borderwidth=10)
    label.pack(side='top') 
    f8=Frame()
    f8.place(x=580,y=50,width='640',height='400')
    btn=Button(f7,text='take photo',width='40',height='1',font=('comicsansms 12 bold'),fg='black',bg='dark grey',borderwidth=10)
    btn.place(x=60,y=150) 
    btn=Button(f7,text='choose from gallery',width='40',height='1',font=('comicsansms 12 bold'),fg='black',bg='dark grey',borderwidth=10)
    btn.place(x=60,y=220) 
    btn=Button(f7,text='open camera',width='40',height='1',font=('comicsansms 12 bold'),fg='black',bg='dark grey',borderwidth=10)
    btn.place(x=60,y=290)
    btn=Button(f7,text='back',width='5',height='1',font=('comicsansms 12 bold'),fg='black',bg='dark grey',borderwidth=10,command=home)
    btn.pack(side="left",anchor="sw")    
    
f1=Frame()   #create login page 1
f1.place(x=0,y=0,width='1280',height='695')
photo=PhotoImage(file="C:\\Users\\dell\\OneDrive\\Desktop\\project\\image2.png")
my_lable=Label(f1,image=photo)
my_lable.place(x=0,y=0)
la=Label(my_lable,text='Enter User id',font=('comicsansms 12 bold'))
la.place(x=230,y=304)
la=Label(f1,text='Enter password',font=('comicsansms 12 bold'))
la.place(x=210,y=345)
username = Entry(font=('Helvetica',15),width='40',borderwidth=5)
password = Entry(font=('Helvetica',15),width='40',borderwidth=5)
username.place(x=350,y=300)
password.place(x=350,y=340)
b2=Button(f1,text="login",font=('comicsansms 12 bold'),borderwidth=5,command=home)
b2.place(x=520,y=380)
win.mainloop()